package IU;

import renderer.RenderGeneral;
import com.jogamp.opengl.GLCapabilities;
import com.jogamp.opengl.GLProfile;
import com.jogamp.opengl.awt.GLCanvas;


public class MasterMind extends javax.swing.JFrame {

    private RenderGeneral RendererEsfera;
    public static GLCanvas glCanvas;
    public static int Solucion[][]= new int[4][3];
    private int c1;
    private int c2;
    private int c3;
    /**
     * Creates new form DemoJOGL
     */
    public MasterMind() {
        colorRandom();
        Solucion[0][0]=c1;
        Solucion[0][1]=c2;
        Solucion[0][2]=c3;
        colorRandom();
        Solucion[1][0]=c1;
        Solucion[1][1]=c2;
        Solucion[1][2]=c3;
        colorRandom();
        Solucion[2][0]=c1;
        Solucion[2][1]=c2;
        Solucion[2][2]=c3;
        colorRandom();
        Solucion[3][0]=c1;
        Solucion[3][1]=c2;
        Solucion[3][2]=c3;
        initComponents();
        RendererEsfera = new RenderGeneral();
        createCanvasJOGL();
        this.setLocationRelativeTo(null);
        this.setSize(800, 800);
        //this.setResizable(false);
    }
    private void colorRandom() {
        switch((int)(Math.random()*5)+1){
            case 1:
                c1=1;
                c2=0;
                c3=0;
                break;
            case 2:
                c1=0;
                c2=1;
                c3=0;
                break;
            case 3:
                c1=0;
                c2=0;
                c3=1;
                break;
            case 4:
                c1=1;
                c2=1;
                c3=0;
                break;
        }
    }
    private void createCanvasJOGL() {
        //only three JOGL lines of code ... and here they are
        GLProfile profile = GLProfile.getDefault();
        GLCapabilities glcaps = new GLCapabilities(profile);
        glCanvas = new GLCanvas(glcaps);
        glCanvas.addGLEventListener(RendererEsfera);
        glCanvas.addMouseListener(RendererEsfera);
        glCanvas.addMouseMotionListener(RendererEsfera);
        glCanvas.setFocusable(true);
        this.panelJOGL.add(glCanvas);
        int w = this.panelJOGL.getWidth();
        int h = this.panelJOGL.getWidth();
        glCanvas.setSize(w, h);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJOGL = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelJOGLLayout = new javax.swing.GroupLayout(panelJOGL);
        panelJOGL.setLayout(panelJOGLLayout);
        panelJOGLLayout.setHorizontalGroup(
            panelJOGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );
        panelJOGLLayout.setVerticalGroup(
            panelJOGLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJOGL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelJOGL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterMind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterMind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterMind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterMind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterMind().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelJOGL;
    // End of variables declaration//GEN-END:variables
}
